// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: sfi.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1000001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(a7e0426a75b80aef);
CAPNP_DECLARE_SCHEMA(c65fdb44562b5be6);

}  // namespace schemas
}  // namespace capnp


static constexpr  ::uint16_t API_VERSION_MAJOR = 0u;
static constexpr  ::uint16_t API_VERSION_MINOR = 0u;
// =======================================================================================

// =======================================================================================


CAPNP_END_HEADER

